feat(outputs.tf): add name_servers for delegation
padok-team/terraform-google-dns pull request #6
Opened 2022-02-01 11:20 UTC by nlevee

2022-02-01 14:14 UTC, JulienJourdain requested changes

2022-02-01 15:38 UTC, nlevee commented on outputs.tf
> +}
I made the modification direct in github editor ... my bad ;-)

2022-02-01 15:41 UTC, nlevee commented
chore(outputs.tf): add an endline

2022-02-11 13:16 UTC, JulienJourdain requested changes

2022-02-11 13:16 UTC, JulienJourdain commented on outputs.tf
> +output "zone_name_servers" {
Yes, I think we should :-) Are you ok with that?

2022-02-11 16:25 UTC, JulienJourdain approved these changes

2022-02-11 16:25 UTC, merged